version: '3.4'

services:
  api:
    restart: always
    environment:
      - GOMEMATIC_API_LOG_LEVEL=debug
      - GOMEMATIC_API_SERVER_HOST=${GOMEMATIC_API_SERVER_HOST:-http://localhost:8080}
      - GOMEMATIC_API_SESSION_SECRET=2eoTUOXc6PA3tYGBcOwVaMHUyFJTC8fz
      - GOMEMATIC_API_ADMIN_EMAIL=admin@webhippie.de
    ports:
      - ${GOMEMATIC_API_SERVER_PORT:-8080}:8080
