[run]
watch_all = true
watch_dirs = ["cmd", "pkg"]
watch_exts = [".go"]
ignore = [".git", "bin", "dist", "storage"]
ignore_files = []
build_delay = 1500
interrupt_timout = 15
graceful_kill = false

init_cmds = [
  ["mkdir", "-p", "storage"],
  ["make", "build"],
  [
    "./bin/gomematic-api",
    "--log-level",
    "debug",
    "server",
    "--session-secret",
    "2NeBoHfeppsgLmTewtcRBLkc",
    "--admin-email",
    "gomematic@webhippie.de"
  ]
]

cmds = [
  ["make", "build"],
  [
    "./bin/gomematic-api",
    "--log-level",
    "debug",
    "server",
    "--session-secret",
    "2NeBoHfeppsgLmTewtcRBLkc",
    "--admin-email",
    "gomematic@webhippie.de"
  ]
]
